# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [3]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
# Create a 1-dimensional NumPy array using np.array()

a=np.array([1,2,3])
a
# Create a 2-dimensional NumPy array using np.array()
b=np.array([[1,2,3],[4,5,6]])
b
# Create a 3-dimensional Numpy array using np.array()
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
a.shape,a.ndim,a.dtype,a.size,type(a)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [6]:
# Attributes of 2-dimensional array
b.shape,b.ndim,b.dtype,b.size,type(b)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [7]:
# Attributes of 3-dimensional array
c.shape,c.ndim,c.dtype,c.size,type(c)

((1, 3, 3), 3, dtype('int64'), 9, numpy.ndarray)

In [8]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(b)
df

0  1  2
0  1  2  3
1  4  5  6

In [9]:
# Create an array of shape (10, 2) with only ones
c=np.ones((10,2))
c

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
# Create an array of shape (7, 2, 3) of only zeros
d=np.zeros((7,2,3))
d

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
# Create an array within a range of 0 and 100 with step 3
ff=np.array(range(0,100,3))
ff

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [12]:
aa=np.random.randint(0,10, size=(7,2))
aa

array([[1, 4],
       [5, 2],
       [0, 9],
       [5, 6],
       [1, 3],
       [0, 1],
       [0, 7]])

In [13]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
bb=np.random.random(size=(3,5))
bb

array([[0.3926098 , 0.93378667, 0.3983919 , 0.88934776, 0.76612484],
       [0.13536095, 0.70968569, 0.73538937, 0.95040662, 0.44820524],
       [0.8058205 , 0.93673049, 0.36994611, 0.23132365, 0.24727102]])

In [14]:
# Set the random seed to 42
kk=np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
gg=np.random.randint(0,10, size=(4,6))
gg

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [15]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
b=np.random.randint(1,10,size=(3,7))
b
# Find the unique numbers in the array you just created
np.unique(b)

# Find the unique numbers in the array you just created


array([1, 2, 3, 4, 5, 7, 9])

In [16]:
# Find the 0'th index of the latest array you created
b[0]

array([9, 1, 3, 7, 4, 9, 3])

In [17]:
# Get the first 2 rows of latest array you created
b[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [18]:
# Get the first 2 values of the first 2 rows of the latest array
b[:2,:2]

array([[9, 1],
       [5, 3]])

In [56]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
pp=np.random.randint(0,10,size=(3,5))
pp
pp1=np.ones((3,5))
pp1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [57]:
# Add the two arrays together
cc=pp+pp1
cc

array([[10.,  7., 10.,  9.,  7.],
       [ 9.,  8.,  2.,  1.,  7.],
       [ 7.,  8.,  5.,  3.,  8.]])

In [58]:
# Create another array of ones of shape (5, 3)
gg=np.ones((5,3))
gg

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
# Try add the array of ones and the other most recent array together
dd=gg+cc
dd

array([[11.,  8., 11., 10.,  8.],
       [10.,  9.,  3.,  2.,  8.],
       [ 8.,  9.,  6.,  4.,  9.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [61]:
# Create another array of ones of shape (3, 5)
oo=np.ones((3,5))
oo

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [63]:
# Subtract the new array of ones from the other most recent array
rr=oo-cc
rr

array([[-9., -6., -9., -8., -6.],
       [-8., -7., -1.,  0., -6.],
       [-6., -7., -4., -2., -7.]])

In [64]:
# Multiply the ones array with the latest array
rr*cc

array([[-90., -42., -90., -72., -42.],
       [-72., -56.,  -2.,   0., -42.],
       [-42., -56., -20.,  -6., -56.]])

In [65]:
# Take the latest array to the power of 2 using '**'
rr**cc
rr

array([[-9., -6., -9., -8., -6.],
       [-8., -7., -1.,  0., -6.],
       [-6., -7., -4., -2., -7.]])

In [73]:
# Do the same thing with np.square()
np.square(rr)

array([[81., 36., 81., 64., 36.],
       [64., 49.,  1.,  0., 36.],
       [36., 49., 16.,  4., 49.]])

In [74]:
# Find the mean of the latest array using np.mean()
np.mean(rr)


np.float64(-5.733333333333333)

In [75]:
# Find the maximum of the latest array using np.max()
np.max(rr)


np.float64(0.0)

In [77]:
# Find the minimum of the latest array using np.min()
np.min(rr)

np.float64(-9.0)

In [78]:
# Find the standard deviation of the latest array
np.std(rr)

np.float64(2.6948510575210314)

In [79]:
# Find the variance of the latest array
np.var(rr)

np.float64(7.2622222222222215)

In [81]:
# Reshape the latest array to (3, 5, 1)
rr.reshape((3,5,1))

array([[[-9.],
        [-6.],
        [-9.],
        [-8.],
        [-6.]],

       [[-8.],
        [-7.],
        [-1.],
        [ 0.],
        [-6.]],

       [[-6.],
        [-7.],
        [-4.],
        [-2.],
        [-7.]]])

In [82]:
# Transpose the latest array
rr.T

array([[-9., -8., -6.],
       [-6., -7., -7.],
       [-9., -1., -4.],
       [-8.,  0., -2.],
       [-6., -6., -7.]])

What does the transpose do?

In [83]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ll=np.random.randint(0,10,size=(3,3))
ll
tt=np.random.randint(0,10,size=(3,2))
tt

array([[6, 6],
       [8, 9],
       [9, 2]])

In [84]:
# Perform a dot product on the two newest arrays you created
ll@tt

array([[ 46,  48],
       [ 62,  52],
       [113,  54]])

In [85]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ee=np.random.randint(0,10,size=(4,3))
ee
yy=np.random.randint(0,10,size=(4,3))
yy

array([[9, 8, 4],
       [5, 3, 9],
       [6, 8, 6],
       [0, 0, 8]])

In [86]:
# Perform a dot product on the two newest arrays you created
ee@yy

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

It doesn't work. How would you fix it?

In [87]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
ee@yy.T

array([[ 66,  57,  54,  24],
       [ 83,  81,  86,  48],
       [102,  93,  96,  48],
       [ 62,  34,  58,   8]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [90]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
aa=np.random.randint(0,10,size=3)
aa
bb=np.random.randint(0,10,size=3)
bb

array([0, 2, 9])

In [91]:
# Compare the two arrays with '>'
aa>bb

array([ True,  True, False])

What happens when you compare the arrays with `>`?

In [92]:
# Compare the two arrays with '>='
aa>=bb

array([ True,  True, False])

In [99]:
# Find which elements of the first array are greater than 7
aa>7
bb>7

array([False, False,  True])

In [100]:
# Which parts of each array are equal? (try using '==')
aa==bb

array([False, False, False])

In [102]:
# Sort one of the arrays you just created in ascending order
np.sort(aa)

array([4, 7, 8])

In [103]:
# Sort the indexes of one of the arrays you just created
np.argsort(aa)

array([2, 0, 1])

In [104]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(aa)

np.int64(1)

In [105]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(aa)

np.int64(2)

In [108]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(aa,axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [109]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(b, axis=0)

array([2, 0, 2, 1, 0, 2, 1])

In [112]:
# Create an array of normally distributed random numbers
uu=np.random.randn(3,5)
uu

array([[-0.25902864, -0.57470921, -0.42149822,  0.33982096, -0.00738015],
       [ 0.76729684, -1.14979258, -0.77533611,  0.77314086, -0.80182784],
       [ 1.38401572,  1.40520531,  1.39232575, -0.88064082,  0.07689495]])

In [118]:
# Create an array with 10 evenly spaced numbers between 1 and 100
ss=np.linspace(1,100,10)
ss

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.